name: Nick
author: ruxmModz
api: 
 - 3.0.0
 - 4.0.0
version: 0.1.5-beta
main: ruxmModz\Nick
commands:
  nick:
    description: Ändere deinen Nicknamen
    aliases: ["nickname"]
    permissions: nick.permissions.command
permissions:
  nick.permissions.command:
    default: false
    description: Ändere deinen Nicknamen
    childs:
