name: Nick
author: ruxmModz
helper: CoolSuper822
api: 
 - 3.0.0
 - 4.0.0
version: b0.1.3
main: ruxmModz\Nick
commands:
  nick:
    description: Ändere deinen Nicknamen
    aliases: ["nickname"]
    permissions: nick.permissions.command
permissions:
  nick.permissions.command:
    default: false
    description: Ändere deinen Nicknamen
    childs: